var annotated_dup =
[
    [ "Area", "class_area.html", "class_area" ],
    [ "ConditionFDiff", "class_condition_f_diff.html", "class_condition_f_diff" ],
    [ "ConditionGrad", "class_condition_grad.html", "class_condition_grad" ],
    [ "ConditionImprovement", "class_condition_improvement.html", "class_condition_improvement" ],
    [ "ConditionIter", "class_condition_iter.html", "class_condition_iter" ],
    [ "ConditionXDiff", "class_condition_x_diff.html", "class_condition_x_diff" ],
    [ "CountCondition", "class_count_condition.html", "class_count_condition" ],
    [ "EpsCondition", "class_eps_condition.html", "class_eps_condition" ],
    [ "Function", "class_function.html", "class_function" ],
    [ "NCube", "class_n_cube.html", "class_n_cube" ],
    [ "NelderMead", "class_nelder_mead.html", "class_nelder_mead" ],
    [ "OptimizationMethod", "class_optimization_method.html", "class_optimization_method" ],
    [ "OptResult", "struct_opt_result.html", "struct_opt_result" ],
    [ "RandomSearch", "class_random_search.html", "class_random_search" ],
    [ "Range", "class_range.html", "class_range" ],
    [ "Simplex", "class_simplex.html", "class_simplex" ],
    [ "SmoothFunction", "class_smooth_function.html", "class_smooth_function" ],
    [ "TerminalCondition", "class_terminal_condition.html", "class_terminal_condition" ],
    [ "TestFunc01", "class_test_func01.html", "class_test_func01" ],
    [ "TestFunc02", "class_test_func02.html", "class_test_func02" ],
    [ "TestFunc03", "class_test_func03.html", "class_test_func03" ],
    [ "TestFunc04", "class_test_func04.html", "class_test_func04" ],
    [ "TestFunc05", "class_test_func05.html", "class_test_func05" ],
    [ "vPoint", "classv_point.html", "classv_point" ]
];